// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odenbatdqohfxgjibkff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZW5iYXRkcW9oZnhnamlia2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODE5OTcsImV4cCI6MjA1OTc1Nzk5N30.P_6OJafAUjC6Z7WYXz2SiD00MD11y7NoQMoWeZYwqOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);